version: '3.4'

services:
  identityservices:
    image: ${DOCKER_REGISTRY-}identityservicesaircraft
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
    ports:
        - "32808:80"
        - "32796:443"
    build:
      context: .
      dockerfile: IdentityServices/Dockerfile
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
    ports: ["1833:1433"]
    volumes:
      ["${APPDATA}/DockerVolumes/sqlserver:/var/opt/mssql/data"]